### ISSUE TITLE
Name / Label Representation

### ISSUE THREAD

**Issue by andrewtj** [oko/rust-dns#13]
Currently domain names are represented as `Vec<String>`. DNS labels may contain arbitrary byte sequences, are compared case insensitively for bytes that fall within the US-ASCII alphabet and may be 1 to 63 bytes, save for the name terminating zero-length root label.

Given this I think a new `Label` type that may only contain 1 to 63 bytes (struct/enum containing `Vec<u8>` or `&[u8]`?) with `Vec<Label>` being implicitly terminated by an empty label would be a worthwhile change. Helpers for working with `Vec<Label>` (appending/prepending labels), marshalling to and from strings (handling escaping to/from presentation form correctly), as well as byte-slice accessors, and converting to DNSSEC canonical form would also be useful.

Does this sound reasonable? If so I'm willing to give it a go if you don't mind working with a newbie.

**Comment by oko** [comment]
Yeah, I agree that there needs to be a stronger API around label handling. This is actually at top of my to-do pile as part of building a name/label API that's suitable for doing proper DNS name compression.

Looking at RFC1035/2181/4343 I think you've covered the bases as far as to-from conversion.

I've been knocking around the idea of using a boxed recursive `Name` type rather than using `Vec<LabelTypeOfWhateverSort>`, which would obviate the need for a separate label type. Something like:

``` rust
pub struct Name<'n> {
    label: &'n [u8]
    parent: Box<Name<'n>>
}
```

Thoughts?

**Comment by andrewtj** [comment]
This might be a bit naive but will that pose any issues for implementing a reverse iterator? (For doing a match down against a zone catalog or the like.)

**Comment by oko** [comment]
Continued in #14
